### ISSUE TITLE
Make 'options' optional in calls, replace with 'WithOptions' method

### ISSUE THREAD

**Issue by EwanValentine** [peak-ai/ais-service-discovery-go#1]
Change API methods from:
`Request(signature, request, options)` to add:
`RequestWithOpts(signature, request, options)`.

Also change Request to `Request(sig, request)`.

Or: `Request(sig, request).WithOptions(opts)`. (if this is possible? Probably not...)

**Comment by vosmith** [comment]
Hey, this issue seemed a little curious to me.  Are you trying to separate `Request(signature, request, options)` into:

`Request(signature, request)`
and
`RequestWithOptions(signature, request, options)`

**Comment by EwanValentine** [comment]
Yeah, I had some feedback suggesting the api was too complex and required too many arguments, so I was thinking of different ways to make things optional or simplify. The options param you currently have to set as `nil`, which isn't very nice really. So I was thinking of having a decorator method which sets the options if required, then simplifying the main methods if that makes sense?
